### ISSUE TITLE
Implement New Cloudflare API Token Feature

### ISSUE THREAD

**Issue by ganeshlohia** [cracker4o/purge-cf-cache-chrome-extension#3]
Cloudflare recently implemented the API Token Service that is more secure and safer than all access API Key. It only involves small minor changes to your code to implement it. Hope to hear back from you soon on this enhancement. Thank you.

Refer: https://api.cloudflare.com/#getting-started-requests for more details.

**Comment by cracker4o** [comment]
@ganeshlohia I implemented the feature last week. I am testing against CF and the feature will be out very soon. Probably by the end of the week. In the meantime you can get the code from the https://github.com/cracker4o/purge-cf-cache-chrome-extension/tree/feature-cf-keys branch and load this as an unpacked extension.

**Comment by ganeshlohia** [comment]
Hi,

Super!!! Thanks for the link. Will test today later in the day.

Regards
Ganesh B Lohia

**Comment by ganeshlohia** [comment]
Hello,

I updated the API Token and then tried to purge from the options page
bottom [Type URLs to Purge]
but it gives a CORS error. And the cache purge fails. I am pretty sure you
are very close to the correct
solution and hope this information helps. In case of any queries, please
let me know. Thank you once
again for your efforts in building this great extension.

Regards
Ganesh B Lohia

**Comment by cracker4o** [comment]
@ganeshlohia  Try copying the manifest file from the chrome folder into the main folder and try to load the extension as an unpacked extension in chrome again. I believe because chrome wasn't finding the manifest file was placing the CORS restriction on your API calls. I am in the final phase of testing so it will be public by the end of the week.

**Comment by cracker4o** [comment]
The new version 1.6.1 is deployed and available for everybody to use. Please read the instructions at https://www.cf-purge.com/token-setup.html about how to setup your API token with the appropriate permissions for the CF-Purge extension.

**Comment by ganeshlohia** [comment]
Hi,

It works flawlessly now. Just as expected. My appreciations
and best wishes to take this extension to the next level.

Thank you.

Regards
Ganesh B Lohia
