### ISSUE TITLE
API token setup instructions wrong

### ISSUE THREAD

**Issue by alex-jitbit** [cracker4o/purge-cf-cache-chrome-extension#4]
https://www.cf-purge.com/token-setup.html on this page.

Why would you need all these permissions, if all you need is "cache purge - purge"? It works - I tested.

**Comment by cracker4o** [comment]
Alex, the zones API call requires the zones permission. The extension uses this call to dynamically determine the zone by the domain which is extracted by the URL you are purging. https://github.com/cracker4o/purge-cf-cache-chrome-extension/blob/master/src/api.js#L34 The purge call requires a valid zone ID to do the purge. https://github.com/cracker4o/purge-cf-cache-chrome-extension/blob/master/src/api.js#L73 Have you tested for accounts with multiple zones per CF account?

**Comment by alex-jitbit** [comment]
Oh I see. Sorry. Yep, I have multiple zones in my account but - and it works just fine. Not sure why :) The only permission I granted was the "purge" one.

Thanks for the tool anyway, it's incredible.

**Comment by cracker4o** [comment]
Maybe they changed something. I'll check their API docs. I haven't checked their API docs in a while.

**Comment by cracker4o** [comment]
They changed their permissions and now the settings are different.
BEFORE:
![image](https://user-images.githubusercontent.com/5861664/99296149-279ff100-27fb-11eb-9ace-afb0bded287b.png)
AFTER:
![image](https://user-images.githubusercontent.com/5861664/99296057-0c34e600-27fb-11eb-9f49-98406775f817.png)

**Comment by cracker4o** [comment]
Closing the issue since the change is made.
